name: FDevelop's Emulator Build

on:
  push:
    branches: [ 'dev', 'main' ]
  pull_request: 
    branches: [ 'dev', 'main' ]

jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@4
      
    - name: Setup JDK
      uses: actions/setup-java@4
      with:
        distribution: 'temurin'
        java_version: '17'
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Setup Grant For Gradle Permissions
      run: chmod +x gradlew

    - name: Run Shared Tests
      run: ./gradlew check

    - name: Build (Debug)
      run: ./gradlew assembleDebug
